name: Build and Push Docker Image

on:
  workflow_dispatch:
    inputs:
      # frontend_version:
      #   description: 'Frontend Version (e.g. 5.5.1)'
      #   required: true
      #   type: string
      backend_version:
        description: 'Backend Version (e.g. 1.1.1)'
        required: true
        type: string

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log into Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ inputs.backend_version }}
            ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
          # build-args: |
          #   FRONTEND_VERSION=${{ inputs.frontend_version }}
          #   BACKEND_VERSION=${{ inputs.backend_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
